ESLint integrado y configurado con prettier
alkemyTech/OT161-React-client pull request #1
Opened 2022-03-18 20:38 UTC by frandepe

ESLint integrado y configurado con prettier

2022-03-19 02:40 UTC, federicomiranda requested changes
Fijate que es un typo simple, nada grave.

Lo que estaría bueno para la próxima es mejorar la descripción del PR. Se puede agregar más detalle de lo que se hizo, por ejemplo, que opciones se agregaron a ESLint, avisar que se agregó Prettier, dejar el número de ticket de Jira, etc.

2022-03-19 02:40 UTC, federicomiranda commented on .prettierrc
> +	"jaxSingleQuote": true,
Esta línea tiene un typo

```suggestion
	"jsxSingleQuote": true,
```

2022-03-19 15:43 UTC, Josem1801 approved these changes

2022-03-20 23:57 UTC, artebleker approved these changes

2022-03-20 23:58 UTC, artebleker commented
Lo veo todo bien. Saludos

2022-03-21 02:30 UTC, federicomiranda commented
> Lo veo todo bien. Saludos

Si lo ves bien hay que mergearlo, no cerrarlo 🤣🤣 
Cuando cerras un PR queda en la nada misma, ahora lo reabro y lo mergeo!

2022-03-21 02:30 UTC, federicomiranda approved these changes
Ahora si!

2022-03-21 02:31 UTC, merged