test contact
alkemyTech/OT161-React-client pull request #113
Opened 2022-04-17 00:02 UTC by frandepe

Los test pasan, pero no estoy seguro de lo que hice.. lo subo con algunas dudas y le hago algunas correcciones si necesario

El test verifica:
-Si se esta llamando a la funcion de submit
-Si los campos de email o telefono son incorrectos, enviando mensajes de error
-Si los datos de envio son correctos

2022-04-19 23:26 UTC, federicomiranda requested changes
Pareciera estar todo bien. Pudiste chequear el tema de las validaciones? Si no hay problema en la validación del input, le pegamos una mirada de nuevo.

Lo que si, por convención la descripción de los tests se suele plantear como una oración que cuente un poco que estas probando. En inglés se empieza por "should", y en español por "debería". Por ejemplo: 

"Debería mostrar un error si el teléfono ingresado es demasiado corto".

Cambia las descripciones de los tests así haces el ejercicio, pero más allá de eso los veo bien

2022-04-20 00:04 UTC, frandepe commented
Ahí corregí el comentario del tests para que sea un poco más descriptivo, cualquier cosa le hago alguna modificación.
El test pasa aunque ponga datos erroneos, eso no me quedó muy claro

2022-04-20 02:32 UTC, federicomiranda commented
Mala mía, me expliqué mal! Me refería a la función de it

```
it("Debería mostrar un error si el teléfono ingresado es demasiado corto", () => {...})
```

2022-04-21 00:07 UTC, frandepe commented
OK genial, ahi entendi. Hecho

2022-04-21 23:33 UTC, federicomiranda approved these changes
Ahora si!

2022-04-21 23:33 UTC, merged