OT161-69:. Método que devuelva el encabezado de seguridad para ser reutilizado en las peticiones a los metodos privados de la AP
alkemyTech/OT161-React-client pull request #19
Opened 2022-03-24 23:44 UTC by Josem1801

Función que verifique la existencia del token en el localStorage y que devuelva un objeto Header Authorization con el valor "Bearer " + el token obtenido, si no encuentra nada devuelve null con un log diciendo que no existe token

2022-03-25 02:54 UTC, federicomiranda requested changes

2022-03-25 02:54 UTC, federicomiranda commented on src/Services/privateApiService.js
>  }
Si esta función recibe el token por parámetro, deberías cada vez que vas a usar el método, antes ejecutar la función que busca el token para recibirlo y pasarselo. No podrías directamente ejecutar la función en la key de Autorization? Si siempre los dos métodos van a convivir en el mismo archivo, no es neceario exportar tokeFromLocalStorage, lo podes usar directamente dentro de todas las otras funciones 🤔

2022-03-25 02:54 UTC, federicomiranda commented on src/Services/privateApiService.js
> +	if (!token) {
Hay un problema común en localStorage, y es que si la API al momento del login devuelve undefined y esa validación no se hace, se guardaría en localStorage el string "undefined" y eso pasaría tu validación correctamente 😛

2022-03-25 15:58 UTC, Josem1801 commented on src/Services/privateApiService.js
>  }
Vale! Entonces remuevo el parametro del token y eso lo obtengo con la función del localstorage

2022-03-27 06:38 UTC, federicomiranda commented on src/Services/privateApiService.js
> +	const headers = { ...tokenFromLocalStorage() };
Es necesario el spread acá? 🤔

2022-03-27 06:38 UTC, federicomiranda approved these changes

2022-03-27 06:38 UTC, merged