@brayanyepes/task/metodo-reutilizable-post
alkemyTech/OT161-React-client pull request #21
Opened 2022-03-25 15:27 UTC by itsbalexy-rockstar

-Método para hacer petición post a los endpoints privados de la api

2022-03-25 20:56 UTC, Boniich requested changes

2022-03-25 20:56 UTC, Boniich commented on src/Services/privateApiService.js
> +        const { data } = await axios.post(`${BASE_URL}${route}`, postData, {headers: {"Authorization": token}});
Yo sacaria el token como parametro y pasaria la funcion dentro de un objeto

algo asi (dentro de la funcion de privatePost):

const headers = {...tokenFromLocalStorage()} y despues pasaria este objeto donde tenes  `{headers: {"Authorization": token}`.

2022-03-27 06:48 UTC, federicomiranda requested changes

2022-03-27 06:48 UTC, federicomiranda commented on src/Services/privateApiService.js
> +const privatePostRequest = async (route, token, postData) => {
No debería recibir el token por parámetros, chequear el método patch que está abajo

2022-03-29 14:03 UTC, Boniich approved these changes

2022-03-29 14:53 UTC, federicomiranda approved these changes

2022-03-29 14:54 UTC, merged