@julian task/card component
alkemyTech/OT161-React-client pull request #29
Opened 2022-03-29 03:08 UTC by artebleker

Cree la carpeta shared dentro de components.
Genere el componente Card reutilizable

2022-03-29 23:37 UTC, federicomiranda commented on src/Components/Shared/Card/Card.js
> +    <section className='cardBody'>
Soy más partidario de la idea que una card se asocia más a un article que a una section 🤔

2022-03-29 23:37 UTC, federicomiranda commented on src/Components/Shared/Card/Card.js
> +   <image className='cardImage' src={image} alt={parser(title)}></image>
No será img el tag? 👀

2022-03-29 23:38 UTC, federicomiranda commented on src/Components/Shared/Card/Card.js
> +   <p className='cardDescription'>{parser(description)}</p>
Si te paso el title como un h2 y un p dentro de description, semánticamente sería bastante complicado. En este caso no dejaría que reciba html la card!

2022-03-29 23:38 UTC, federicomiranda commented on src/Components/Shared/Card/card.css
> +    height: 350px;
Ojo con el uso de px 🤔

2022-03-29 23:39 UTC, federicomiranda requested changes
Algunos ajustes para que quede óptimo

2022-03-30 15:00 UTC, artebleker commented on src/Components/Shared/Card/Card.js
> +   <p className='cardDescription'>{parser(description)}</p>
corregido

2022-03-30 15:01 UTC, artebleker commented on src/Components/Shared/Card/Card.js
> +    <section className='cardBody'>
siempre es confusa la diferencia y cuando aplicarlo, pero si tiene más sentido
ahi lo corregi

2022-03-31 01:28 UTC, federicomiranda approved these changes

2022-03-31 01:28 UTC, merged