Componente de listado de miembros
alkemyTech/OT161-React-client pull request #33
Opened 2022-03-29 19:18 UTC by Boniich

Tarea: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT161/boards/234?modal=detail&selectedIssue=OT161-67

- Componente que contiene las propiedades name, image, description, facebookUrl y linkedinUrl para renderizar la informacion en cada caso
- Logica para renderizar el listado de miembros de la ONG
- Faltarian los estilos para el componente de UI, que seran agregados mas adelante

2022-03-29 23:51 UTC, federicomiranda requested changes

2022-03-29 23:51 UTC, federicomiranda commented on src/Components/About/Members.js
> +	};
Esto necesita un try catch, que pasa si falla la request?

2022-03-30 00:58 UTC, Boniich commented on src/Components/About/Members.js
> +	};
listo. Tambien agregue un pequeño mensaje para renderizar en caso de algo falle en la peticion

2022-03-31 01:32 UTC, federicomiranda approved these changes
👌🏼

2022-03-31 01:32 UTC, merged