user http service
alkemyTech/OT161-React-client pull request #34
Opened 2022-03-29 23:40 UTC by artebleker

Agregue en la carpeta Service el conjunto de servicios hacia usuarios.

2022-03-29 23:52 UTC, federicomiranda requested changes

2022-03-29 23:52 UTC, federicomiranda commented on src/Services/UsersHTTPService.js
> +    }
Todo necesita try catch, que pasa si falla algunas de las requests? 👀

2022-03-30 13:52 UTC, artebleker commented on src/Services/UsersHTTPService.js
> +    }
Ahí esta solucionado

2022-03-30 15:09 UTC, Boniich commented on src/Services/UsersHTTPService.js
> +    }
todos esos metodos no deberian tener un `return` para que devuelva la promesa?

2022-03-31 01:33 UTC, federicomiranda submitted a review, later dismissed
Me olvide de lo que sumó @Boniich, los métodos no están retornando nada, solo hacen el await!

2022-04-01 15:13 UTC, artebleker commented
Ahora espero este bien XD

2022-04-01 15:30 UTC, Boniich approved these changes
Todo perfecto. Pero aun @federicomiranda tiene que aceptar su cambio solicitado para mergear xD

2022-04-01 21:33 UTC, merged