servicio base extendido al form de slide
alkemyTech/OT161-React-client pull request #36
Opened 2022-03-30 01:20 UTC by frandepe

Conecté el componente SlidesForm.js al servicio base

2022-03-31 01:39 UTC, federicomiranda requested changes
Podes revisar que ya tenemos algún ejemplo mergeado!

2022-03-31 01:39 UTC, federicomiranda commented on src/Services/publicApiService.js
> +}
Este es solo un método de slides, habría que hacer todos, en un archivo propio y usando los privados!

2022-03-31 21:08 UTC, Boniich commented
esta perfecto, lo unico no entendi mucho porque hay un `publicPathMethod` en el publicApiService, no encontre ninguna tarea asi, no se si esta con otro nombre pero el resto parece estar re bien. Igual hay que esperar a que Fede apruebe el cambio solicitado

2022-04-01 21:25 UTC, Boniich approved these changes

2022-04-01 21:28 UTC, merged