OT161-89: Crear variables de entorno
alkemyTech/OT161-React-client pull request #51
Opened 2022-04-01 14:40 UTC by Josem1801

Se agrego un servicio para los testimonios y se configuraron las variables de entorno de la ruta.
Se utilizo la variable de entorno REACT_APP_BASE_URL ya establecida.

2022-04-01 17:08 UTC, Boniich requested changes

2022-04-01 17:08 UTC, Boniich commented on src/Services/testimonialService.js
> +}
estaria bueno cambiar esos metodos de peticiones publicas por los privados

2022-04-01 23:17 UTC, Josem1801 commented on src/Services/testimonialService.js
> +}
Vale! El get no se si sea necesario pero aun asi lo cambie Jajajja

2022-04-02 00:41 UTC, Boniich approved these changes
perfecto

2022-04-02 00:42 UTC, merged