variable de entorno de contacts
alkemyTech/OT161-React-client pull request #60
Opened 2022-04-02 02:50 UTC by frandepe

- Agregué variable de entorno y modifique el contactService.js
- También corregí un error en el archivo para renderizar texto html (RenderHTML.js)

2022-04-02 21:13 UTC, artebleker approved these changes

2022-04-03 00:53 UTC, Boniich requested changes

2022-04-03 00:53 UTC, Boniich commented on src/Services/contactService.js
> +		const { data } = await getDataMethod(
esta usando el metodo publico

2022-04-03 00:53 UTC, Boniich commented on src/Services/contactService.js
> +		const { data } = await getDataMethod(
esta usando el metodo publico

2022-04-03 00:54 UTC, Boniich commented
solo ese detalle en ambos metodos, despues esta todo perfecto

2022-04-03 16:10 UTC, federicomiranda requested changes
Aplicar los cambios pedidos por @Boniich

2022-04-03 18:09 UTC, frandepe commented
perfecto, corregido

2022-04-05 02:28 UTC, federicomiranda approved these changes
Ahora si

2022-04-05 02:29 UTC, merged