variable News & fix newsService
alkemyTech/OT161-React-client pull request #62
Opened 2022-04-02 15:26 UTC by artebleker

Agregue la variable de entorno News
Y modifique el newService para que trabaje con esta variable

2022-04-02 23:02 UTC, Boniich requested changes

2022-04-02 23:02 UTC, Boniich commented on src/Services/newService.js
> +	return response;
le faltan los try catch (ya faltaban de antes pero estaria bueno agregarselos)

2022-04-02 23:02 UTC, Boniich commented on src/Services/newService.js
>  };
try catch aca tambien

2022-04-03 15:00 UTC, artebleker commented on src/Services/newService.js
> +	return response;
ya me había pasado la otra vez!
Gracias, ahí lo corregí

2022-04-03 15:01 UTC, Boniich approved these changes

2022-04-03 15:01 UTC, merged