@Boniich/task/modularizar rutas 2
alkemyTech/OT161-React-client pull request #86
Opened 2022-04-08 19:15 UTC by Boniich

Task: https://alkemy-labs.atlassian.net/browse/OT161-114?atlOrigin=eyJpIjoiMzJiOGI4MTM2Njk2NGQ3ZDk1OTZjYWIwYmJmNmQxZWUiLCJwIjoiaiJ9

Se crea un archivo para las rutas publicas y un archivo para las rutas privadas
Se modulariza el App.js usando estos componentes que internamente tienen las rutas (publicas o privadas/protegidas)

Nota: yo no puede probar como funciona la animacion de con el componente <AnimatedSwitch> porque no me anda y no puedo instalar la libreria pero creo que deberia funcionar bien

2022-04-09 18:00 UTC, artebleker approved these changes
Se ve bien,
Entiendo que Fran también toco .App asi que capaz hay que recorregir alguna cosa una vez este todo mergeado

2022-04-10 15:02 UTC, federicomiranda requested changes

2022-04-10 15:02 UTC, federicomiranda commented on src/App.js
> +				<Route>
Este Route no está de mas? 🤔

2022-04-10 15:02 UTC, federicomiranda commented on src/routes/BackOfficeRutes.js
> +		<TransitionSwitch>
Si el transition switch ya lo tenes el componente que va a contener a este (el App.js), es necesario volver a definirlo? Estaríamos teniendo un transition switch adentro de otro. No podríamos usar un fragment acá?

2022-04-10 15:02 UTC, federicomiranda commented on src/routes/PublicWebRutes.js
> +		<TransitionSwitch>
Misma duda de antes. Es necesario el transition switch? No podemos usar un fragment?

2022-04-10 16:37 UTC, Boniich commented on src/App.js
> +				<Route>
No, es necesario, porque sino tiene ese route, te manda un 404 cuando intentas entrar en una parte del backoffice

2022-04-10 16:40 UTC, Boniich commented on src/routes/BackOfficeRutes.js
> +		<TransitionSwitch>
No, porque sino ejecuta varias rutas al mismo tiempo en una sola pantalla

por ejemplo:

- pantalla de actividades
- error 404 

esos dos los pone pegados en la misma pantalla, y si le das para ver los detalles de alguna actividad, te lo pone arriba de todo en la misma pantalla.

yo entiendo por fragment esto: `<></>` o esto, que creo que es lo mismo `<Fragment></Fragment>`, no se, quizas le estoy errando ahi

2022-04-12 02:25 UTC, federicomiranda approved these changes

2022-04-12 02:25 UTC, merged